[package]
name = "webr-bundle"
version = "0.1.0"
edition = "2021"
authors = ["Andrés F. Quintero <afquinteromoreano@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4.4.0"
clap = { version = "4.4.4", features = ["derive"] }
colored = "2.0.4"
env_logger = "0.10.0"
flate2 = "1.0.27"
futures = "0.3.28"
hyper = { version = "0.14.27", features = ["full"] }
ignore = "0.4.20"
log = "0.4.20"
regex = "1.9.5"
reqwest = { version = "0.11.20", default-features = false, features = ["stream", "rustls", "rustls-tls"] }
serde = { version = "1.0.188", features = ["derive", "rc"] }
serde_json = "1.0.107"
tar = "0.4.40"
tokio = { version = "1.32.0", features = ["full"] }
